### ISSUE TITLE
Not all patches show up on a ticket

### ISSUE THREAD

**Issue by nicholasray** [j4n-co/pherrit#2]
### Steps to Reproduce 

1. Notice the patches on the ticket depicted in the image
<img width="313" alt="pherrit" src="https://user-images.githubusercontent.com/3496279/47872921-7970ac80-ddd5-11e8-8606-ab4369326051.png">
2. Notice that https://gerrit.wikimedia.org/r/#/c/mediawiki/skins/MinervaNeue/+/470917 is not included in that list

### Expected Results

Pherrit displays all patches on the ticket

### Actual Results

Pherrit omits some patches

### Testing Environment for QA
Readers-Web-Kanbanana-Board-2018-19-Q2

Browser Version
Chrome 70.0.3538.77

OS Version
macOS High Sierra (10.13.5)

Pherrit Version
1.1

**Comment by nicholasray** [comment]
The plot thickens. When I refreshed my browser, I now see the patch (No Minerva variables...) correctly showing up:

<img width="306" alt="screen shot 2018-11-01 at 1 12 39 pm" src="https://user-images.githubusercontent.com/3496279/47873850-ed13b900-ddd7-11e8-89cc-d986f6c6dad3.png">

**Comment by jandre3000** [comment]
I think I found the issue. For some reason I was just appending the first-child element to the card, instead of all available elements https://github.com/j4n-co/pherrit/commit/eba7d5ff011b67231b7fd460074a9e9e8f1e73e3#diff-5f1825c5f33f5fdbe7e31cc76f941efa
