### ISSUE TITLE
Link from chromestore is to non-existent github.io page

### ISSUE THREAD

**Issue by edg2s** [j4n-co/pherrit#3]
The "Website" link here: https://chrome.google.com/webstore/detail/pherrit/polcefipbgcdfkpbmmbdjgkgfgjoebij goes to https://j4n-co.github.io/pherrit/ which is a 404.

**Comment by jandre3000** [comment]
Changed this to point to the github page https://chrome.google.com/webstore/detail/pherrit/polcefipbgcdfkpbmmbdjgkgfgjoebij
