### ISSUE TITLE
Unnecessary vertical scrollbars in Chrome+Ubuntu

### ISSUE THREAD

**Issue by edg2s** [j4n-co/pherrit#4]
Appearing everywhere for me. Chrome 72 + Ubuntu 18.04.
![image](https://user-images.githubusercontent.com/180672/53262199-e59d5600-36cd-11e9-912a-bdfb478d14e0.png)

**Comment by MatmaRex** [comment]
I noticed this too, on Windows. Clearly Jan develops on a Mac ;)
